steps:

# github clone
#- name: 'gcr.io/cloud-builders/git'
#  args: ['clone', 'https://github.com/GalchenkoAlexander/ch17-hive.git']

# Copying hive files to GCS
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  - 'cp'
  - 'src/main/hive/*'
  - 'gs://${PROJECT_ID}-artifacts/ch17-hive/hive/'
  volumes:
    - path: '/.'
      name: 'source'

# Exec maven package
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package', '-DoutputDirectory=target']
  volumes:
    - path: '/target'
      name: 'target'

# Copying jars files to GCS
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - 'cp'
    - '-r'
    - 'target/*.jar'
    - 'gs://${PROJECT_ID}-artifacts/ch17-hive/jars/'
  volumes:
    - path: '/target'
      name: 'target'
