steps:


    #
    # Assembly spark artifact, run unit tests
    #
    # TODO: add '-Dsbt.ivy.home=/cache/.ivy2'
  - name: 'mozilla/sbt:8u212_1.2.8'
    args: ['sbt', '-Dsbt.global.base=/cache/.sbt-home', 'assembly']
    id: 'build_spark_jar'
    dir: 'spark/'

  #
  # Update manifest file and upload artifacts
  #

  - name: gcr.io/$PROJECT_ID/manifest-util
    args: ['--git_sha',    '$COMMIT_SHA',
           '--git_brunch', '$BRANCH_NAME',
           '--build_id', '$BUILD_ID',
           '--upload'
           ]
    id: 'set-manifest'
    dir: 'spark/'
