substitutions:

steps:
  # Run test

  # github clone
  - name: 'gcr.io/cloud-builders/git'
    id: 'clone gcp-cicd'
    args: ['clone', 'https://github.com/elisska/gcp-cicd.git', '/gcp-cicd']
    volumes:
      - path: '/gcp-cicd'
        name: 'repository'

<<<<<<< HEAD
  - name: elisska/docker-airflow:latest
    id: 'init'
=======
  - name: puckel/docker-airflow:latest
    id: 'initdb'
>>>>>>> 87dd79607acac255135b63f8b158ea56d967dfdf
    args: ['airflow', 'initdb']
    volumes:
      - path: '/gcp-cicd'
        name: 'repository'
<<<<<<< HEAD
      - path: '/usr'
        name: 'airflow_server'

  - name: elisska/docker-airflow:latest
=======
      - path: '/usr/local/airflow'
        name: 'airflow_home'


  - name: puckel/docker-airflow:latest
    id: 'pip_install.sh'
    entrypoint: 'bash'
    args: ['/gcp-cicd/airflow/pip_install.sh', '/usr/local/airflow/venv', '/gcp-cicd/airflow']
    volumes:
      - path: '/gcp-cicd'
        name: 'repository'
      - path: '/usr/local/airflow'
        name: 'airflow_home'








  - name: puckel/docker-airflow:latest
    id: 'test-validation'
>>>>>>> 87dd79607acac255135b63f8b158ea56d967dfdf
    entrypoint: 'python'
    args: ['dags-validation-test.py']
    dir: '/gcp-cicd/airflow/test/validation/'
    env:
      - 'AIRFLOW__CORE__LOAD_EXAMPLES=False'
      - 'AIRFLOW__CORE__DAGS_FOLDER=/gcp-cicd/airflow/dags'
    volumes:
      - path: '/gcp-cicd'
        name: 'repository'
<<<<<<< HEAD
      - path: '/usr'
        name: 'airflow_server'

  - name: elisska/docker-airflow:latest
    args: ['env']
    id: 'show env'
    volumes:
      - path: '/gcp-cicd'
        name: 'repository'
      - path: '/usr'
        name: 'airflow_server'

  - name: elisska/docker-airflow:latest
=======
      - path: '/usr/local/airflow'
        name: 'airflow_home'

#  - name: puckel/docker-airflow:latest
#    id: 'show env'
#    args: ['env']
#    volumes:
#      - path: '/gcp-cicd'
#        name: 'repository'
#      - path: '/airflow_home'
#        name: 'airflow_home'
#
#  - name: puckel/docker-airflow:latest
#    id: 'cat airflow.cfg'
#    args: ['cat', '/usr/local/airflow/airflow.cfg']
#    volumes:
#      - path: '/gcp-cicd'
#        name: 'repository'
#      - path: '/airflow_home'
#        name: 'airflow_home'

#  - name: puckel/docker-airflow:latest
#    id: 'pwd'
#    args: ['pwd']
#    volumes:
#      - path: '/gcp-cicd'
#        name: 'repository'
#      - path: '/usr/local/airflow'
#        name: 'airflow_home'

#  - name: puckel/docker-airflow:latest
#    id: 'ls'
#    args: ['ls', '-la', '/usr/local/airflow']
#    volumes:
#      - path: '/gcp-cicd'
#        name: 'repository'
#      - path: '/usr/local/airflow'
#        name: 'airflow_home'


  - name: puckel/docker-airflow:latest
    id: 'test-definition'
>>>>>>> 87dd79607acac255135b63f8b158ea56d967dfdf
    entrypoint: 'python'
    args: ['sample-dag-hive-ephemeral-definition-test.py']
    dir: '/gcp-cicd/airflow/test/definition/'
    env:
      - 'AIRFLOW__CORE__LOAD_EXAMPLES=False'
      - 'AIRFLOW__CORE__DAGS_FOLDER=/gcp-cicd/airflow/dags'
    volumes:
      - path: '/gcp-cicd'
        name: 'repository'
<<<<<<< HEAD
      - path: '/usr'
        name: 'airflow_server'
=======
      - path: '/usr/local/airflow'
        name: 'airflow_home'
>>>>>>> 87dd79607acac255135b63f8b158ea56d967dfdf

  # Copying DAG files to GCS
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'composer'
      - 'environments'
      - 'storage'
      - 'dags'
      - 'import'
      - '--environment=${_COMPOSER_ENV_NAME}'
      - '--location=${_COMPOSER_REGION}'
      - '--source=${_SOURCE}'


#images: [
#  'apache/airflow:master-python3.7-ci'
#  'puckel/docker-airflow:latest'
#]
