steps:

# github clone
#- name: 'gcr.io/cloud-builders/git'
#  args: ['clone', 'https://github.com/GalchenkoAlexander/ch17-hive.git']


# Exec maven package
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
  dir: 'hive/'

- name: gcr.io/$PROJECT_ID/manifest-util
  args: ['--git_sha', '$COMMIT_SHA',
         '--git_branch', '$BRANCH_NAME',
         '--build_id', '$BUILD_ID',
         '--upload' ]
  id: 'set-manifest'
  dir: 'hive/'
