steps:


    #
    # Assembly spark artifact, run unit tests
    #
    # TODO: add '-Dsbt.ivy.home=/cache/.ivy2'
  - name: 'mozilla/sbt:8u212_1.2.8'
    args: ['sbt', '-Dsbt.global.base=/cache/.sbt-home', 'assembly']
    id: 'build_spark_jar'
    dir: 'spark/'

  #
  # Update manifest file and upload artifacts
  #

  - name: gcr.io/infra-core-us-central/manifest-util
    args: ['--git_sha', '$COMMIT_SHA',
           '--git_brunch', '$BRANCH_NAME',
           '--built_at', '12-12-12',
           '--upload',
           '--mf_file', './.mf.json'
           ]
    id: 'set-manifest'
    dir: 'spark/'
    waitFor: ['build_spark_jar']



images: [
  'mozilla/sbt:8u212_1.2.8',
  'gcr.io/infra-core-us-central/manifest-util'
]
