substitutions:
  SOURCE: 'airflow/dags/*'

steps:

  # Copying DAG files to GCS
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'composer'
      - 'environments'
      - 'storage'
      - 'dags'
      - 'import'
      - '--environment=${COMPOSER_ENV_NAME}'
      - '--location=${COMPOSER_REGION}'
      - '--source=${SOURCE}'


