substitutions:
  _BUILD_BUCKET: gcp-cicd-artifacts1

steps:
  # Run test

  # github clone
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/elisska/gcp-cicd.git', '/gcp-cicd']
  volumes:
    - path: '/gcp-cicd'
      name: 'repository'

  # can be moved to docker file
  - name: elisska/docker-airflow:latest
    id: 'init'
    args: ['airflow', 'initdb']
    volumes:
      - path: '/gcp-cicd'
        name: 'repository'
      - path: '/usr/local/airflow'
        name: 'airflow_server'

  # run validation tests
  - name: elisska/docker-airflow:latest
    entrypoint: 'python'
    args: ['dags-validation-test.py']
    dir: '/gcp-cicd/airflow/test/validation/'
    id: 'test-validation'
    env:
      - 'AIRFLOW__CORE__LOAD_EXAMPLES=False'
      - 'AIRFLOW__CORE__DAGS_FOLDER=/gcp-cicd/airflow/dags'
    volumes:
      - path: '/gcp-cicd'
        name: 'repository'
      - path: '/usr/local/airflow'
        name: 'airflow_server'

  # run definition tests
  - name: elisska/docker-airflow:latest
    entrypoint: 'python'
    args: ['sample-dag-hive-ephemeral-definition-test.py']
    dir: '/gcp-cicd/airflow/test/definition/'
    id: 'test-definition'
    env:
      - 'AIRFLOW__CORE__LOAD_EXAMPLES=False'
      - 'AIRFLOW__CORE__DAGS_FOLDER=/gcp-cicd/airflow/dags'
    volumes:
      - path: '/gcp-cicd'
        name: 'repository'
      - path: '/usr/local/airflow'
        name: 'airflow_server'

  # Copying DAG files to GCS
  # perhaps this step has to be moved from this build
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'composer'
      - 'environments'
      - 'storage'
      - 'dags'
      - 'import'
      - '--environment=${_COMPOSER_ENV_NAME}'
      - '--location=${_COMPOSER_REGION}'
      - '--source=${_SOURCE}'

# Copying input datasets to GCS
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - 'cp'
    - '-r'
    - '/gcp-cicd/airflow/dags/*'
    - 'gs://${_BUILD_BUCKET}/${REPO_NAME}/${BRANCH_NAME}/${SHORT_SHA}/airflow/dags/'
  volumes:
    - path: '/gcp-cicd'
      name: 'repository'

#images: [
#  'apache/airflow:master-python3.7-ci'
#  'elisska/docker-airflow:latest'
#]
