steps:

    #
    # Assembly spark artifact, run unit tests
    #
    # NOTE: '-Dsbt.global.base=/cache/.sbt-home', '-Dsbt.ivy.home=/cache/.ivy2',
  - name: 'mozilla/sbt:8u212_1.2.8'
    args: ['sbt',  'assembly']
    id: 'build_spark_jar'
    dir: 'spark/'
    waitFor: ['-']

    #
    # Upload Spark artifacts to GS
    #
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'publish_spark_artifact'
    args: [
      'cp',
      'target/scala-2.11/*assembly*.jar',
      'gs://$_BUILD_BUCKET/${REPO_NAME}/${BRANCH_NAME}/${SHORT_SHA}/spark/app.jar'
    ]
    dir: 'spark/'


    #
    # Deploy spark jar to the cloud composer env
    #
  - name: gcr.io/cloud-builders/gcloud
    args: ['composer', 'environments',
    'run', '${_COMPOSER_ENV_NAME}',
    '--location', '${_COMPOSER_REGION}',
    'variables',
    '--',
    '--set', 'spark__mainJarFileUri', 'gs://$_BUILD_BUCKET/${REPO_NAME}/${BRANCH_NAME}/${SHORT_SHA}/spark/app.jar']
    id: 'set-composer-jar-ref'
    waitFor: ['publish_spark_artifact']

substitutions:
  _COMPOSER_REGION: us-central1
  _COMPOSER_ENV_NAME: gcp-test-env-2
  _BUILD_BUCKET: cicd

images: [
  'mozilla/sbt:8u212_1.2.8'
]
