steps:
  # can be moved to docker file
  - name: elisska/docker-airflow:latest
    id: 'airflow-initdb'
    args: ['airflow', 'initdb']
    volumes:
      - path: '/usr/local/airflow'
        name: 'airflow_server'

  # run validation tests
  - name: elisska/docker-airflow:latest
    entrypoint: 'python'
    args: ['test/validation/dags-validation-test.py']
    dir: 'airflow/'
    id: 'test-validation'
    env:
      - 'AIRFLOW__CORE__LOAD_EXAMPLES=False'
      - 'AIRFLOW__CORE__DAGS_FOLDER=dags/'
    volumes:
      - path: '/usr/local/airflow'
        name: 'airflow_server'

  # run definition tests
  - name: elisska/docker-airflow:latest
    entrypoint: 'python'
    args: ['test/definition/sample-dag-hive-ephemeral-definition-test.py']
    dir: 'airflow/'
    id: 'test-definition'
    env:
      - 'AIRFLOW__CORE__LOAD_EXAMPLES=False'
      - 'AIRFLOW__CORE__DAGS_FOLDER=./dags'
    volumes:
      - path: '/usr/local/airflow'
        name: 'airflow_server'

    # Copying DAG files to GCS
  - name: gcr.io/$PROJECT_ID/manifest-util
    args: ['--git_sha', '$COMMIT_SHA',
           '--git_brunch', '$BRANCH_NAME',
           '--build_id', '$BUILD_ID',
           '--upload' ]
    id: 'set-manifest'
    dir: 'airflow/'