steps:

# Exec maven package
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
  dir: 'hive/'

- name: gcr.io/$PROJECT_ID/manifest-util
  args: ['--git_sha', '$COMMIT_SHA',
         '--git_brunch', '$BRANCH_NAME',
         '--build_id', '$BUILD_ID',
         '--upload' ]
  id: 'set-manifest'
  dir: 'hive/'
